### ISSUE TITLE
Incorrect info output for large directories

### ISSUE THREAD

**Issue by prahkila** [CSCfi/ida2-command-line-tools#6]
ida info command produces incorrect output for large directories.
Some filenames are truncated and/or replaced by html code snippets.
Erroneous lines can be easily located since they end in carriage return ("\r" "^M").

As an example, I have a directory containing 840 files, info output [r54-info.txt](https://github.com/CSCfi/ida2-command-line-tools/files/5376522/r54-info.txt).
Errors can be found on lines 50, 153, 197, 344, 535, 770
Issue is reproducible, also on different clients. 

Info output would be needed for custom download script since downloading TB sized zip files is not practical.

**Comment by patrick-stickler-csc-fi** [comment]
Hello. I'm sorry to hear about this bug. Can you please send a report to support@csc.fi so that it can be handled via our support system? Thanks.

**Comment by patrick-stickler-csc-fi** [comment]
Sorry, the correct email address is servicedesk@csc.fi

**Comment by prahkila** [comment]
Done.

**Comment by patrick-stickler-csc-fi** [comment]
release-2020-10-20 of the IDA Command Line Tools resolves the reported bug.
